### ISSUE TITLE
WHO_AM_I reads, compass doesn't

### ISSUE THREAD

**Issue by ghost** [kriswiner/MPU-9250#3]
<pre>
<code>
MPU9250 I AM 71 I should be 71
MPU9250 is online...
x-axis self test: acceleration trim within : -0.4% of factory value
y-axis self test: acceleration trim within : -0.2% of factory value
z-axis self test: acceleration trim within : 0.2% of factory value
x-axis self test: gyration trim within : -0.1% of factory value
y-axis self test: gyration trim within : -0.1% of factory value
z-axis self test: gyration trim within : 0.2% of factory value
MPU9250 initialized for active data mode....
AK8963 I AM FF I should be 48
AK8963 initialized for active data mode....
X-Axis sensitivity adjustment value 1.26
Y-Axis sensitivity adjustment value 0.52
Z-Axis sensitivity adjustment value 0.94
ax = 37.35 ay = 37.29 az = 37.23 mg
gx = 4.26 gy = 4.25 gz = 4.24 deg/s
mx = -470 my = -120 mz = -125 mG
q0 = 1.00 qx = 0.00 qy = 0.00 qz = 0.00
Yaw, Pitch, Roll: -13.80, 0.00, 0.00
rate = 0.56 Hz
ax = 37.35 ay = 37.29 az = 37.23 mg
gx = 4.26 gy = 4.25 gz = 4.24 deg/s
mx = 16961 my = -120 mz = -122 mG
q0 = 1.00 qx = 0.00 qy = 0.00 qz = 0.00
Yaw, Pitch, Roll: -13.80, 0.00, 0.00
rate = 602.14 Hz
</code></pre>

None of these values change when I move the chip.

<pre><code>
 // Configure Interrupts and Bypass Enable 
// Set interrupt pin active high, push-pull, hold interrupt pin level HIGH until interrupt cleared, 
// clear on read of INT_STATUS, and enable I2C_BYPASS_EN so additional chips 
// can join the I2C bus and all can be controlled by the Arduino as master writeByte(MPU9250_ADDRESS, INT_PIN_CFG, 0x22); 
writeByte(MPU9250_ADDRESS, INT_ENABLE, 0x01);  // Enable data ready (bit 0) interrupt
</code></pre>

is set, so it should be in bypass mode and the compass WHO_AM_I register should read, right? This might be entirely a hardware problem.

**Comment by kriswiner** [comment]
I don't know if you just copied the code a bit strangely but you have to be sure the MPU9250 is in bypass mode to access the magnetometer data; this means this register write:

writeByte(MPU9250_ADDRESS, INT_PIN_CFG, 0x22);

has to occur. In the GitHub sketch this write is done as part of the MPU9250 initialization; the magnetometer initialization occurs afterwards.

It looks like you are accessing the mag sensitivity properly, but your accel, gyro and mag data are complete garbage. Are you using the Wire.h library for I2C? I suspect you have an I2C problem, or, as you suspect, a bad MPU9250 breakout board. Are you using the EMSENSR-9250 BOB or one of a Chinese import? What are you using for pull-up resistor values. 4K7 is appropriate.

**Comment by kriswiner** [comment]
Did you make any progress of this issue?

**Comment by ghost** [comment]
Yeah-- I was using a custom breakout board and didn't ground RESV, so it was a hardware problem. Sorry for committing a software issue without thoroughly proofing out the board-- thanks for getting back to me on it!

**Comment by kriswiner** [comment]
Glad you got it fixed!

**Comment by saeednayeri89** [comment]
hi i have problem with mpu9250 i can read all axis perfectly but in magnetometer it doesn't respond . i enable bypass mode but nothing appear . this is my code i work with atmega2561 
 #define mpu_9250_ID 0xD0
#define mag_9250_ID 0x0c
#define	GYRO_FULL_SCALE_250_DPS		0x00
#define	GYRO_FULL_SCALE_500_DPS		0x08
#define	GYRO_FULL_SCALE_1000_DPS	0x10
#define	GYRO_FULL_SCALE_2000_DPS	0x18
#define	ACC_FULL_SCALE_2_G	0x00
#define	ACC_FULL_SCALE_4_G	0x08
#define	ACC_FULL_SCALE_8_G	0x10
#define	ACC_FULL_SCALE_16_G	0x18
#define SELF_TEST_X_GYRO	0
#define SELF_TEST_Y_GYRO	1
#define SELF_TEST_Z_GYRO	2
#define SELF_TEST_X_ACCEL	13
#define SELF_TEST_Y_ACCEL	14
#define SELF_TEST_Z_ACCEL	15
#define XG_OFFS_ET_H		19
#define XG_OFFS_ET_L		20
#define YG_OFFSET_H			21
#define YG_OFFSET_L			22
#define ZG_OFFSET_H			23
#define ZG_OFFSET_L			24
#define SMPLRT_DIV			25
#define CONFIG				26
#define GYRO_CONFIG			27
#define ACCEL_CONFIG		28
#define ACCEL_CONFIG2		29
#define LP_ACCEL_ODR		30
#define WOM_THR				31
#define FIFO_EN				35
#define I2C_MST_CTRL		36
#define I2C_SLV0_ADDR		37
#define I2C_SLV0_REG		38
#define I2C_SLV0_CTRL		39
#define I2C_SLV1_ADDR		40
#define I2C_SLV1_REG		41
#define I2C_SLV1_CTRL		42
#define I2C_SLV2_ADDR		43
#define I2C_SLV2_REG		44
#define I2C_SLV2_CTRL		45
#define I2C_SLV3_ADDR		46
#define I2C_SLV3_REG		47
#define I2C_SLV3_CTRL		48
#define I2C_SLV4_ADDR		49
#define I2C_SLV4_REG		50
#define I2C_SLV4_DO			51
#define I2C_SLV4_CTRL		52
#define I2C_SLV4_DI			53
#define I2C_MST_STATUS		54
#define INT_PIN_CFG			55
#define INT_ENABLE			56
#define INT_STATUS			58
#define ACCEL_XOUT_H		59
#define ACCEL_XOUT_L		60
#define ACCEL_YOUT_H		61
#define ACCEL_YOUT_L		62
#define ACCEL_ZOUT_H		63
#define ACCEL_ZOUT_L		64
#define TEMP_OUT_H			65
#define TEMP_OUT_L			66
#define GYRO_XOUT_H			67
#define GYRO_XOUT_L			68
#define GYRO_YOUT_H			69
#define GYRO_YOUT_L			70
#define GYRO_ZOUT_H			71
#define GYRO_ZOUT_L			72
#define EXT_SENS_DATA_00	73
#define EXT_SENS_DATA_01	74
#define EXT_SENS_DATA_02	75
#define EXT_SENS_DATA_03	76
#define EXT_SENS_DATA_04	77
#define EXT_SENS_DATA_05	78
#define EXT_SENS_DATA_06	79
#define EXT_SENS_DATA_07	80
#define EXT_SENS_DATA_08	81
#define EXT_SENS_DATA_09	82
#define EXT_SENS_DATA_10	83
#define EXT_SENS_DATA_11	84
#define EXT_SENS_DATA_12	85
#define EXT_SENS_DATA_13	86
#define EXT_SENS_DATA_14	87
#define EXT_SENS_DATA_15	88
#define EXT_SENS_DATA_16	89
#define EXT_SENS_DATA_17	90
#define EXT_SENS_DATA_18	91
#define EXT_SENS_DATA_19	92
#define EXT_SENS_DATA_20	93
#define EXT_SENS_DATA_21	94
#define EXT_SENS_DATA_22	95
#define EXT_SENS_DATA_23	96
#define I2C_SLV0_DO			99
#define I2C_SLV1_DO			100
#define I2C_SLV2_DO			101
#define I2C_SLV3_DO			102
#define I2C_MST_DELAY_CTRL	103
#define SIGNAL_PATH_RESET	104
#define MOT_DETECT_CTRL		105
#define USER_CTRL			106
#define PWR_MGMT_1			107
#define PWR_MGMT_2			108
#define FIFO_COUNTH			114
#define FIFO_COUNTL			115
#define FIFO_R_W			116
#define WHO_AM_I			117
#define XA_OFFSET_H			119
#define XA_OFFSET_L			120
#define YA_OFFSET_H			122
#define YA_OFFSET_L			123
#define Z_A_OFFSET_H		125
#define Z_A_OFFSET_L		126
#define WIA 0x00
#define INFO 0x01
#define ST1 0x02
#define HXL 0x03
#define HXH 0x04 
#define HYL 0x05
#define HYH 0x06
#define HZL 0x07
#define HZH 0x08
#define ST2 0x09
#define CNTL 0x0A
#define RSV 0x0B
#define ASTC 0x0C
#define TS1 0x0D
#define TS2 0x0E
#define CDIS 0x0F
#define ASAX 0x10
#define ASAY 0x11
#define ASAZ 0x12
#define twi_speed 100000
void twi_init(void){
	TWSR=0x00;
	TWBR=(F_CPU-(16*twi_speed))/(twi_speed*2);//   12= 400khz , twps=0
	TWCR=0x04;
}
unsigned char twi_readstatus (void){
	unsigned char status=0;
	status=TWSR & 0xf8;
	return status;
}
void twi_start (void){
	TWCR = (1<<TWINT)|(1<<TWSTA)|(1<<TWEN);
	while  ((TWCR & (1<<TWINT))==0);
}
void twi_Address(unsigned int ADD){
	TWDR = ADD;
	TWCR = (1<<TWINT) | (1<<TWEN);
	while  ((TWCR & (1<<TWINT))==0);
}
void twi_stop (void){
	TWCR = (1<<TWINT)|(1<<TWEN)|(1<<TWSTO);
}
unsigned char twi_read_data (unsigned int device,unsigned int address_r){
	twi_start();
	twi_Address(device);
	twi_Address(address_r);
	twi_start();
	twi_Address(device+1);
	TWCR = (1<<TWINT) | (1<<TWEN) ;
	while  ((TWCR & (1<<TWINT))==0);
	twi_stop();
	return TWDR;
	_delay_ms(50);	
}
void twi_write_data (unsigned int device,unsigned int address_w,unsigned int data_w){
	twi_start();
	twi_Address(device);
	twi_Address(address_w);
	TWDR=data_w;
	TWCR = (1<<TWINT) | (1<<TWEN);
	while  ((TWCR & (1<<TWINT))==0);
	twi_stop();
	_delay_ms(50);
}
void mpu_9250_init(void){
 	//twi_write_data(mpu_9250_ID,PWR_MGMT_1,0x80);//reset mpu9250
 	twi_write_data(mpu_9250_ID,CONFIG,0x06); // 5HZ band width
 	twi_write_data(mpu_9250_ID,GYRO_CONFIG,GYRO_FULL_SCALE_250_DPS);
 	twi_write_data(mpu_9250_ID,ACCEL_CONFIG,ACC_FULL_SCALE_2_G);
 	twi_write_data(mpu_9250_ID,ACCEL_CONFIG2,0x06);// 5 HZ band width
	twi_write_data(mpu_9250_ID,PWR_MGMT_1,0x00);
 	twi_write_data(mpu_9250_ID,PWR_MGMT_2,0x00);
	twi_write_data(mpu_9250_ID,INT_PIN_CFG,0x02);
	//twi_write_data(mpu_9250_ID,INT_ENABLE,0x08);
 	//twi_write_data(mag_9250_ID,RSV,0x01); 
 	twi_write_data(mag_9250_ID,CNTL,0x11);
}
void getting_sensors(void){
	mag_x=twi_read_data(mag_9250_ID,WIA);
 	x_in=(twi_read_data(mpu_9250_ID,ACCEL_XOUT_H)<<8)+twi_read_data(mpu_9250_ID,ACCEL_XOUT_L)>>5;
 	y_in=(twi_read_data(mpu_9250_ID,ACCEL_YOUT_H)<<8)+twi_read_data(mpu_9250_ID,ACCEL_YOUT_L)>>5;
 	roll_in=((twi_read_data(mpu_9250_ID,GYRO_XOUT_H)<<8)+ twi_read_data(mpu_9250_ID,GYRO_XOUT_L))>>5;
 	pitch_in=((twi_read_data(mpu_9250_ID,GYRO_YOUT_H)<<8)+twi_read_data(mpu_9250_ID,GYRO_YOUT_L))>>5;
 	yaw_in=((twi_read_data(mpu_9250_ID,GYRO_ZOUT_H)<<8)+twi_read_data(mpu_9250_ID,GYRO_ZOUT_L))>>5;
	temp_in=(twi_read_data(mpu_9250_ID,TEMP_OUT_H)<<8)+twi_read_data(mpu_9250_ID,TEMP_OUT_L);
}

**Comment by kriswiner** [comment]
I can't diagnose your code, do you get an ACK on 0x0C?

**Comment by kriswiner** [comment]
Also, are you reading the mag ST2 status register along with the six data
bytes? Must do.

**Comment by saeednayeri89** [comment]
Thank you for your email , I have not ack on 0x0c I can't read wia reg in mag

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by saeednayeri89** [comment]
I first read the data ready bit and wait to be one next read the data and at Finnish reg read std2

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kriswiner** [comment]
If you get no ACK at 0x0C you will never read mag. Run an I2C scan to
verify you can see the mag at 0x0c. See:

void I2Cscan()
{
// scan for i2c devices
  byte error, address;
  int nDevices;

  Serial.println("Scanning...");

  nDevices = 0;
  for(address = 1; address < 127; address++ )
  {
    // The i2c_scanner uses the return value of
    // the Write.endTransmisstion to see if
    // a device did acknowledge to the address.
    Wire.beginTransmission(address);
    error = Wire.endTransmission();

    if (error == 0)
    {
      Serial.print("I2C device found at address 0x");
      if (address<16)
        Serial.print("0");
      Serial.print(address,HEX);
      Serial.println("  !");

      nDevices++;
    }
    else if (error==4)
    {
      Serial.print("Unknow error at address 0x");
      if (address<16)
        Serial.print("0");
      Serial.println(address,HEX);
    }
  }
  if (nDevices == 0)
    Serial.println("No I2C devices found\n");
  else
    Serial.println("done\n");

}
}

**Comment by saeednayeri89** [comment]
OK  I do it and email the result for you , i must enable bypass mode first then scan for address? if doest respond for any address?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by saeednayeri89** [comment]
hi  again thank you for your good program

i change it to my code and find the device ID , i can read all the reg in continue mode 1 , thanks for every thing and one more question i want to ask is how can i change these values to degree for my quadcopter ?

my robot is stable and smooth with accu and gyro but i want to add mag into it and i dont know how to change these mag values to degree may i ask you to help if you have time please.

here is my code work perfectly :

#define mpu_9250_ID 0xD0
#define mag_9250_ID 0x18
#define GYRO_FULL_SCALE_250_DPS 0x00
#define GYRO_FULL_SCALE_500_DPS 0x08
#define GYRO_FULL_SCALE_1000_DPS 0x10
#define GYRO_FULL_SCALE_2000_DPS 0x18
#define ACC_FULL_SCALE_2_G 0x00
#define ACC_FULL_SCALE_4_G 0x08
#define ACC_FULL_SCALE_8_G 0x10
#define ACC_FULL_SCALE_16_G 0x18
#define SELF_TEST_X_GYRO 0
#define SELF_TEST_Y_GYRO 1
#define SELF_TEST_Z_GYRO 2
#define SELF_TEST_X_ACCEL 13
#define SELF_TEST_Y_ACCEL 14
#define SELF_TEST_Z_ACCEL 15
#define XG_OFFS_ET_H 19
#define XG_OFFS_ET_L 20
#define YG_OFFSET_H 21
#define YG_OFFSET_L 22
#define ZG_OFFSET_H 23
#define ZG_OFFSET_L 24
#define SMPLRT_DIV 25
#define CONFIG 26
#define GYRO_CONFIG 27
#define ACCEL_CONFIG 28
#define ACCEL_CONFIG2 29
#define LP_ACCEL_ODR 30
#define WOM_THR 31
#define FIFO_EN 35
#define I2C_MST_CTRL 36
#define I2C_SLV0_ADDR 37
#define I2C_SLV0_REG 38
#define I2C_SLV0_CTRL 39
#define I2C_SLV1_ADDR 40
#define I2C_SLV1_REG 41
#define I2C_SLV1_CTRL 42
#define I2C_SLV2_ADDR 43
#define I2C_SLV2_REG 44
#define I2C_SLV2_CTRL 45
#define I2C_SLV3_ADDR 46
#define I2C_SLV3_REG 47
#define I2C_SLV3_CTRL 48
#define I2C_SLV4_ADDR 49
#define I2C_SLV4_REG 50
#define I2C_SLV4_DO 51
#define I2C_SLV4_CTRL 52
#define I2C_SLV4_DI 53
#define I2C_MST_STATUS 54
#define INT_PIN_CFG 55
#define INT_ENABLE 56
#define INT_STATUS 58
#define ACCEL_XOUT_H 59
#define ACCEL_XOUT_L 60
#define ACCEL_YOUT_H 61
#define ACCEL_YOUT_L 62
#define ACCEL_ZOUT_H 63
#define ACCEL_ZOUT_L 64
#define TEMP_OUT_H 65
#define TEMP_OUT_L 66
#define GYRO_XOUT_H 67
#define GYRO_XOUT_L 68
#define GYRO_YOUT_H 69
#define GYRO_YOUT_L 70
#define GYRO_ZOUT_H 71
#define GYRO_ZOUT_L 72
#define EXT_SENS_DATA_00 73
#define EXT_SENS_DATA_01 74
#define EXT_SENS_DATA_02 75
#define EXT_SENS_DATA_03 76
#define EXT_SENS_DATA_04 77
#define EXT_SENS_DATA_05 78
#define EXT_SENS_DATA_06 79
#define EXT_SENS_DATA_07 80
#define EXT_SENS_DATA_08 81
#define EXT_SENS_DATA_09 82
#define EXT_SENS_DATA_10 83
#define EXT_SENS_DATA_11 84
#define EXT_SENS_DATA_12 85
#define EXT_SENS_DATA_13 86
#define EXT_SENS_DATA_14 87
#define EXT_SENS_DATA_15 88
#define EXT_SENS_DATA_16 89
#define EXT_SENS_DATA_17 90
#define EXT_SENS_DATA_18 91
#define EXT_SENS_DATA_19 92
#define EXT_SENS_DATA_20 93
#define EXT_SENS_DATA_21 94
#define EXT_SENS_DATA_22 95
#define EXT_SENS_DATA_23 96
#define I2C_SLV0_DO 99
#define I2C_SLV1_DO 100
#define I2C_SLV2_DO 101
#define I2C_SLV3_DO 102
#define I2C_MST_DELAY_CTRL 103
#define SIGNAL_PATH_RESET 104
#define MOT_DETECT_CTRL 105
#define USER_CTRL 106
#define PWR_MGMT_1 107
#define PWR_MGMT_2 108
#define FIFO_COUNTH 114
#define FIFO_COUNTL 115
#define FIFO_R_W 116
#define WHO_AM_I 117
#define XA_OFFSET_H 119
#define XA_OFFSET_L 120
#define YA_OFFSET_H 122
#define YA_OFFSET_L 123
#define Z_A_OFFSET_H 125
#define Z_A_OFFSET_L 126
#define WIA 0x00
#define INFO 0x01
#define ST1 0x02
#define HXL 0x03
#define HXH 0x04
#define HYL 0x05
#define HYH 0x06
#define HZL 0x07
#define HZH 0x08
#define ST2 0x09
#define CNTL 0x0A
#define RSV 0x0B
#define ASTC 0x0C
#define TS1 0x0D
#define TS2 0x0E
#define CDIS 0x0F
#define ASAX 0x10
#define ASAY 0x11
#define ASAZ 0x12
#define twi_speed 100000
void twi_init(void){
TWSR=0x00;
TWBR=(F_CPU-(16*twi_speed))/(twi_speed*2);//   12= 400khz , twps=0
TWCR=0x04;
}
unsigned char twi_readstatus (void){
unsigned char status=0;
status=TWSR & 0xf8;
return status;
}
void twi_start (void){
TWCR = (1<<TWINT)|(1<<TWSTA)|(1<<TWEN);
while  ((TWCR & (1<<TWINT))==0);
}
void twi_Address(unsigned int ADD){
TWDR = ADD;
TWCR = (1<<TWINT) | (1<<TWEN);
while  ((TWCR & (1<<TWINT))==0);
}
void twi_stop (void){
TWCR = (1<<TWINT)|(1<<TWEN)|(1<<TWSTO);
}
unsigned char twi_read_data (unsigned int device,unsigned int address_r){
twi_start();
twi_Address(device);
//twi_status=twi_readstatus();
twi_Address(address_r);
twi_start();
twi_Address(device+1);
TWCR = (1<<TWINT) | (1<<TWEN) ;
while  ((TWCR & (1<<TWINT))==0);
twi_stop();
return TWDR;
_delay_ms(50);
}
void twi_write_data (unsigned int device,unsigned int address_w,unsigned int data_w){
twi_start();
twi_Address(device);
twi_status=twi_readstatus();
twi_Address(address_w);
TWDR=data_w;
TWCR = (1<<TWINT) | (1<<TWEN);
while  ((TWCR & (1<<TWINT))==0);
twi_stop();
_delay_ms(50);
}
void mpu_9250_init(void){
  twi_write_data(mpu_9250_ID,PWR_MGMT_1,0x80);//reset mpu9250
_delay_ms(500);
  twi_write_data(mpu_9250_ID,CONFIG,0x06); // 5HZ band width
  twi_write_data(mpu_9250_ID,GYRO_CONFIG,GYRO_FULL_SCALE_250_DPS);
twi_write_data(mpu_9250_ID,ACCEL_CONFIG,ACC_FULL_SCALE_2_G);
  twi_write_data(mpu_9250_ID,ACCEL_CONFIG2,0x06);// 5 HZ band width
twi_write_data(mpu_9250_ID,PWR_MGMT_1,0x00);
  twi_write_data(mpu_9250_ID,PWR_MGMT_2,0x00);
twi_write_data(mpu_9250_ID,INT_PIN_CFG,0x02);
  twi_write_data(mag_9250_ID,CNTL,0x12);
}
void getting_sensors(void){
  mag_x=(twi_read_data(mag_9250_ID,HXH)<<8)+twi_read_data(mag_9250_ID,HXL);
mag_y=(twi_read_data(mag_9250_ID,HYH)<<8)+twi_read_data(mag_9250_ID,HYL);
mag_z=(twi_read_data(mag_9250_ID,HZH)<<8)+twi_read_data(mag_9250_ID,HZL);
twi_read_data(mag_9250_ID,ST2);
  x_in=(twi_read_data(mpu_9250_ID,ACCEL_XOUT_H)<<8)+twi_read_data(mpu_9250_ID,ACCEL_XOUT_L)>>5;
  y_in=(twi_read_data(mpu_9250_ID,ACCEL_YOUT_H)<<8)+twi_read_data(mpu_9250_ID,ACCEL_YOUT_L)>>5;
roll_in=((twi_read_data(mpu_9250_ID,GYRO_XOUT_H)<<8)+ twi_read_data(mpu_9250_ID,GYRO_XOUT_L))>>5;
pitch_in=((twi_read_data(mpu_9250_ID,GYRO_YOUT_H)<<8)+twi_read_data(mpu_9250_ID,GYRO_YOUT_L))>>5;
yaw_in=((twi_read_data(mpu_9250_ID,GYRO_ZOUT_H)<<8)+twi_read_data(mpu_9250_ID,GYRO_ZOUT_L))>>5;
temp_in=(twi_read_data(mpu_9250_ID,TEMP_OUT_H)<<8)+twi_read_data(mpu_9250_ID,TEMP_OUT_L);
}



________________________________

**Comment by kriswiner** [comment]
Check here for open source sensor fusion methods:

https://github.com/kriswiner/Butterfly/blob/master/MPU9250_MS5637_BasicAHRS2_Butterfly.ino

**Comment by saeednayeri89** [comment]
Thank for your answer and your time

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by saeednayeri89** [comment]
hi
i cant understand about how to calibrate the compass
in lcd when show 90 degree its wrong what i see is larger than 120 degree what can i do for this ?
is there a simple formula for compass output ?
thanks
________________________________

**Comment by kriswiner** [comment]
https://github.com/kriswiner/MPU6050/wiki/Simple-and-Effective-Magnetometer-Calibration

**Comment by saeednayeri89** [comment]
i don't know what to do  I know this is simple problem for you but i cant analyze that how i must do this
sorry for bad english
________________________________

**Comment by saeednayeri89** [comment]
Hi again i just want to say thank you for your help and your time
I can now get 3 axis mag data and calcute degree and calibrate mag but when i saw the degree in LCD it just have tolerance like noise how we can fix this ?
I set the mag output data in 16 bit
________________________________

**Comment by kriswiner** [comment]
Did you calibrate all of your sensors? How do you know?

**Comment by saeednayeri89** [comment]
I can see output on LCD I just set the x , y ,z to north and note the difrence from zero and add the difrence to program

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kriswiner** [comment]
This is not sensor calibration.

**Comment by saeednayeri89** [comment]
I don't understand that code and i don't know what to do

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kriswiner** [comment]
This is as simple as I know how to make it, better ask at Sparkfun or
Adafruit then:

https://github.com/kriswiner/MPU6050/wiki/Simple-and-Effective-Magnetometer-Calibration

**Comment by saeednayeri89** [comment]
Thanks for link
My ASAx,y,z reg are different and these reg are readable only what can I do for it ?
And for external mag field can I use self test?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
