### ISSUE TITLE
Magnetometer values return 0. "AK8963 I AM FF I should be 48"

### ISSUE THREAD

**Issue by evenfl** [kriswiner/MPU-9250#342]
Hi,

I'm currently trying to get euler angles from my MPU9250. My problem is the magnetometer. I've tried different libraries and the only value I get from mx, my and mz is 0. 

I'm using Arduino Nano. Here's my wiring:

VCC  ------ 3.3V
GND ------ GND
SDA  ------- A4
SCL   ------- A5
INT   ------- 2
NCS  ------- 3.3V
FSYNC ----- GND

In addition, I have external pull-up resistors (10K) connected to SDA and SCL. I am using your MPU9250BasicAHRS.ino.

When scanning for I2C devices I only find 0x68. I tried bypassing by adding the following lines of code, hoping that it would help me communicate with the AK8963.

// Configure Interrupts and Bypass Enable
// Set interrupt pin active high, push-pull, hold interrupt pin level HIGH until interrupt cleared,
// clear on read of INT_STATUS, and enable I2C_BYPASS_EN so additional chips
// can join the I2C bus and all can be controlled by the Arduino as master
myIMU.writeByte(MPU9250_ADDRESS, INT_PIN_CFG, 0x37);
myIMU.writeByte(MPU9250_ADDRESS, INT_ENABLE, 0x38); // Enable data ready (bit 0) interrupt
delay(100);

It did not work. I2C scanning gives me the same results and the magnetometer still returns 0 for mx, my and mz.

I'm starting to think that the magnetometer is faulty, but I'm hoping that you have some other suggestions to my problem. Thanks in advance!

![mpu9250-900x700](https://user-images.githubusercontent.com/43533364/51787821-c6ff7a00-2176-11e9-96f9-4b08916c5d3f.jpg)

**Comment by kriswiner** [comment]
???

myIMU.writeByte(MPU9250_ADDRESS, INT_PIN_CFG, 0x37);
myIMU.writeByte(MPU9250_ADDRESS, INT_ENABLE, 0x38); // Enable data ready
(bit 0) interrupt

You are writing into reserved bits in these registers. Why?

Why not try:

myIMU.writeByte(MPU9250_ADDRESS, INT_PIN_CFG, 0x12);
myIMU.writeByte(MPU9250_ADDRESS, INT_ENABLE, 0x01); // Enable data ready
(bit 0) interrupt

**Comment by evenfl** [comment]
Thanks for the response! Whoops, my bad.. Unfortunately, your suggestion didn't change the result.

**Comment by kriswiner** [comment]
Try with a different sensor...

**Comment by evenfl** [comment]
Tried a different sensor and it works. Thanks a lot for all the work you put in Kris. Not all heroes wear capes!
