### ISSUE TITLE
IMU Data Read

### ISSUE THREAD

**Issue by rafaybeg** [kriswiner/MPU-9250#348]
Hey, I am new to IMU and Arduinos and I am trying to get an Arduino to work with IMU with proper calibration. I using the code MPU9250_MS5637_AHRS_t3. I removed teh code for the pressure sensor and the display, however when I run the code, I don't get any data for. Everything shows up as 0. I am using an Arduino Uno with IMU 9250. I have attached the code I am using.
![capture](https://user-images.githubusercontent.com/47674071/52878279-db091c80-3121-11e9-944a-1ea9dedc96cb.PNG)
[MPU9250_MS5637_AHRS_t3.zip](https://github.com/kriswiner/MPU9250/files/2870462/MPU9250_MS5637_AHRS_t3.zip)

**Comment by kriswiner** [comment]
Are you (properly) using the interrupt?

**Comment by rafaybeg** [comment]
It worked, I was using the wrong pin. Thanks!
