### ISSUE TITLE
Is this possible only with MPU9250?

### ISSUE THREAD

**Issue by borstan** [kriswiner/MPU-9250#380]
Hello guys, 

I have a question if this (https://youtu.be/BXsGWoOMtmU) is possible only with the MPU9250.  Because when I was reading through issues Kris said that it's impossible to cover all the positions (see #374). Is this only possible with added pressure sensor? 

Or what should be added to be able to track 3D position like this? (https://youtu.be/6ijArKE8vKU)

Thank you for your replies.

**Comment by kriswiner** [comment]
A well-chosen 9 DoF IMU plus adequate calibration +  accurate sensor fusion
for absolute orientation estimation + a barometer for altitude estimation
should be able to reproduce this demonstration but keep in mind even
relative position estimation using these alone via dead reckoning will have
position errors that grow quadratically with time. It won't be very
accurate after even a short time.
