### ISSUE TITLE
faster ahrs updates? 

### ISSUE THREAD

**Issue by bradBot5** [kriswiner/MPU-9250#394]
Mr. Winer,
Is it possible to get faster ahrs updates on a pro mini by modifiying the code? Or is that a limitation of MCU speed? (currently getting new data every half second or so) 

also, is this where I would plug in my calibration data:

float magCalibration[3] = {0, 0, 0}, magbias[3] = {0, 0, 0};  // Factory mag calibration and mag bias
float gyroBias[3] = {0, 0, 0}, accelBias[3] = {0, 0, 0};      // Bias corrections for gyro and accelerometer

Thanks!

**Comment by kriswiner** [comment]
Every half second is the display speed only, this you can change in the
sketch. The limitation of fusion rate is the AVR architecture and MCU clock
speed, which will limit you to ~100 Hz fusion udpate rate.

Might try one of these
<https://www.tindie.com/products/tleracorp/ladybug-stm32l432-development-board/>
.

**Comment by bradBot5** [comment]
Cool thanks. Can you point me to the line for the display speed please?

**Comment by bradBot5** [comment]
is it these ones?
uint32_t delt_t = 0; // used to control display output rate
uint32_t count = 0, sumCount = 0; // used to control display output rate

**Comment by bradBot5** [comment]
ok fixed display speed issue:

// Serial print and/or display at 0.5 s rate independent of data rates
    delt_t = millis() - count;
    if (delt_t > 20) { // update LCD once per half-second independent of read rate  *** was 500  displays approximately 30fps at 20 milliseconds in stead of half second

Thanks
