### ISSUE TITLE
stabilisation YAW

### ISSUE THREAD

**Issue by hicode-and** [kriswiner/MPU-9250#427]
Hi, again thanks for your work.
I have a issue/question.
I'm interesseted on watching the YAW.
Its good (not a big drift) but when you move the sensor (for exemple 30°), the Yaw take a long time to stabilize to the good value (about 30-40 seconds). It is normal? I have a bug ?

thx for help

**Comment by kriswiner** [comment]
What is your fusion rate? I would guess that if you are working with an AVR
MCU it will be quite low. If you run the gyro sample rate at 200 - 400 Hz
you will need to iterate the fusion filter 10 - 20 times for each new gyro
data set. So you will need fusion rates of 2 - 10 kHz. Better use this
<https://www.tindie.com/products/tleracorp/ladybug-stm32l432-development-board/>or
something like it.

**Comment by korbinianbauer** [comment]
Is your Magnetometer properly calibrated?
Even though I'm using an Arduino Mega, I get stable (+-1°) values after <0.5s again.

**Comment by kriswiner** [comment]
Ok, sounds like everything is working then...
