### ISSUE TITLE
"MPU9250 I AM 70 I should be 71"

### ISSUE THREAD

**Issue by Andyinater** [kriswiner/MPU-9250#458]
I am not sure what to do here. This was followed up with "Could not connect to MPU9250: 0x70"

**Comment by kriswiner** [comment]
You have some other IC, not the MPU9250. MPU9255 is 0x73. 0x70 probably
refers to some Chinese custom variant or a knockoff.

Simply switch the test for 0x71 to 0x70 and the sketch should run.

**Comment by Andyinater** [comment]
Thank you! This clears up many of the problems I have been facing.
