### ISSUE TITLE
MPU9250 interrupt pin not working

### ISSUE THREAD

**Issue by XZheng0427** [kriswiner/MPU-9250#488]
I have to configure the interrupts in the MPU set up to be active high, push-pull. However, I checked the oscilloscope that it is not working as expected.

Do you have any ideas about this issue?
Many thanks.

Below screenshot is the MPU9250 init.

![Screenshot 2023-04-05 120029](https://user-images.githubusercontent.com/97288936/230061954-2931f201-c9af-4340-8c5d-0fdfd1c35dbe.png)

**Comment by kriswiner** [comment]
Not sure if you are using an Arduino IDE or not, looks like maybe the ST
HAL but do you not need to assign a certain pin of your MCU as interrupt
and set its mode to INPUT?

**Comment by kriswiner** [comment]
As far as setting the MPU9250 interrupt configuration, the two lines look
correct to me. Problem might be in the way you are te==reating the MCU pins
or fake MPU9250....

**Comment by XZheng0427** [comment]
Hi Kriswiner,

I used the STM32H7 to connect the MPU9250.
I used the oscilloscope to check the MPU9250 INT pin, no high level output.
Also, I configured the GPIO of STM32H7 as GPIO_MODE_IT_RISING, and I checked the GPIO EXIT interrupt that is work. Please see the below figure.
![image](https://user-images.githubusercontent.com/97288936/230141061-89b18c36-c7a8-4316-b998-22bb44b411d3.png)

Many thanks

**Comment by XZheng0427** [comment]
However, I can read the MPU9250 raw data, i.e., Accel, Gyro, Temp, using the below function.
![image](https://user-images.githubusercontent.com/97288936/230142338-2e43807b-d13e-4086-8492-86f60a0c5d9e.png)

**Comment by kriswiner** [comment]
Usually, to get the MPU9250 to enable the interrupt, just those two
register writes to INT_CFG and INT_EN are required. This is what I do:

writeByte(MPUnum, INT_PIN_CFG, 0x10); // INT is 50 microsecond pulse and *any
read to clear*
writeByte(MPUnum, INT_ENABLE, 0x01); // Enable data ready (bit 0) interrupt

So if you do not select "any read to clear" you will have to manually clear
the interrupt, this is probably why it is not working. Check the data sheet
what 0x22 is selecting....you might be latching the interrupt or who knows
what...

**Comment by XZheng0427** [comment]
According to your configuration,  I tried that.
The interrupt pin is working.
Appreciate your help.
Many thanks

**Comment by kriswiner** [comment]
Glad I could help.
